# -*- coding: utf-8 -*-
"""CustomizedDataSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVRxppmN8LcX8Zd3o2Nfz48Fy7KDmomK
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

# Dataset manually created
data = {
    "RollNumber": list(range(1, 31)),
    "Name": [
        "Ahmed", "Fatima", "Ali", "Ayesha", "Hassan", "Zainab", "Umar", "Sana", "Bilal", "Maria",
        "Saad", "Hina", "Imran", "Nadia", "Salman", "Amina", "Kamran", "Rabia", "Faisal", "Sara",
        "Shahid", "Iqra", "Tariq", "Mehreen", "Asad", "Saba", "Junaid", "Nida", "Zeeshan", "Noor"
    ],
    "Marks": [
        85, 78, 90, 60, 55, 88, 70, 65, 95, 50,
        72, 68, 80, 77, 62, 85, 58, 90, 75, 60,
        53, 82, 68, 74, 66, 80, 90, 55, 72, 59
    ],
    "Height": [
        170, 165, 172, 160, 158, 168, 164, 162, 175, 155,
        163, 161, 167, 166, 159, 170, 157, 173, 165, 160,
        156, 169, 162, 164, 161, 168, 172, 158, 163, 159
    ],
    "Grade": [
        'A', 'B', 'A', 'C', 'D', 'A', 'B', 'C', 'A', 'D',
        'B', 'C', 'B', 'B', 'C', 'A', 'D', 'A', 'B', 'C',
        'D', 'A', 'C', 'B', 'C', 'B', 'A', 'D', 'B', 'C'
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Features and target
X = df[['Marks', 'Height']]
y = df['Grade']

# Encode Grade labels to numeric
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.3, random_state=42
)

# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

# Predict on test data
y_pred = knn.predict(X_test)

# Evaluate performance on test data
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report (Test Data):")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Evaluate performance on training data
y_train_pred = knn.predict(X_train)
print("\nTraining Accuracy:", accuracy_score(y_train, y_train_pred))


# Optional: Show test data with predictions and names
test_results = X_test.copy()
test_results['Actual_Grade'] = le.inverse_transform(y_test)
test_results['Predicted_Grade'] = le.inverse_transform(y_pred)
test_results['Name'] = df.loc[test_results.index, 'Name']
print("\nTest set predictions:")
print(test_results[['Name', 'Marks', 'Height', 'Actual_Grade', 'Predicted_Grade']])