# -*- coding: utf-8 -*-
"""Fuzzy_reasoning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153ISDeynT_dLyjph9b25FcKTulLqUc6t
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# Restaurant Tipping System
def restaurant_tipping():
    # Define input and output variables
    service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
    food = ctrl.Antecedent(np.arange(0, 11, 1), 'food')
    tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')

    # Define membership functions
    service.automf(3)
    food.automf(3)
    tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
    tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
    tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])

    # Define fuzzy rules
    rule1 = ctrl.Rule(service['poor'] | food['poor'], tip['low'])
    rule2 = ctrl.Rule(service['average'], tip['medium'])
    rule3 = ctrl.Rule(service['good'] | food['good'], tip['high'])

    # Create control system
    tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    tipping = ctrl.ControlSystemSimulation(tipping_ctrl)

    # Input values
    tipping.input['service'] = 6.5
    tipping.input['food'] = 9.8

    # Compute the result
    tipping.compute()

    # Print and visualize the result
    print(f"Tip: {tipping.output['tip']:.2f}")
    tip.view(sim=tipping)

# ABS Brake System
def abs_brake_system():
    # Define input and output variables
    speed = ctrl.Antecedent(np.arange(0, 101, 1), 'speed')
    slip = ctrl.Antecedent(np.arange(0, 11, 1), 'slip')
    brake = ctrl.Consequent(np.arange(0, 101, 1), 'brake')

    # Define membership functions
    speed.automf(3)
    slip.automf(3)
    brake['low'] = fuzz.trimf(brake.universe, [0, 0, 50])
    brake['medium'] = fuzz.trimf(brake.universe, [0, 50, 100])
    brake['high'] = fuzz.trimf(brake.universe, [50, 100, 100])

    # Define fuzzy rules
    rule1 = ctrl.Rule(speed['poor'] | slip['poor'], brake['high'])
    rule2 = ctrl.Rule(speed['average'], brake['medium'])
    rule3 = ctrl.Rule(speed['good'] | slip['good'], brake['low'])

    # Create control system
    braking_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    braking = ctrl.ControlSystemSimulation(braking_ctrl)

    # Input values
    braking.input['speed'] = 70
    braking.input['slip'] = 3

    # Compute the result
    braking.compute()

    # Print and visualize the result
    print(f"Brake: {braking.output['brake']:.2f}")
    brake.view(sim=braking)

# Run the systems
restaurant_tipping()
abs_brake_system()
plt.show()

"""This code demonstrates the application of fuzzy logic using the `scikit-fuzzy` library in Python. Fuzzy logic is a method of reasoning that resembles human reasoning, allowing for approximate rather than fixed and exact values. It's particularly useful in control systems where precise mathematical models are difficult to define.

The script defines two independent fuzzy logic control systems:

1.  **Restaurant Tipping System**: Calculates a tip percentage based on service and food quality.
2.  **ABS Brake System**: Determines brake pressure based on vehicle speed and wheel slip.

### Core Components of a Fuzzy Logic System (`skfuzzy`)

*   **Antecedent (Input Variable)**: These are the input conditions to the fuzzy system (e.g., `service`, `food`, `speed`, `slip`). They are defined over a specific range (`np.arange`).
*   **Consequent (Output Variable)**: This is the output of the fuzzy system (e.g., `tip`, `brake`). It's also defined over a range.
*   **Membership Functions (MFs)**: These functions define how well a specific value belongs to a fuzzy set (e.g., 'poor', 'average', 'good' service). `skfuzzy` provides methods like `automf` (automatically generates MFs) and `trimf` (triangular membership function) to define these.
*   **Fuzzy Rules**: These are IF-THEN statements that link the input fuzzy sets to the output fuzzy sets (e.g., "IF service is good THEN tip is high"). Logical operators like `|` (OR) and `&` (AND) are used.
*   **Control System**: This combines the antecedents, consequents, and rules into a complete fuzzy logic system.
*   **Control System Simulation**: This object allows you to input specific crisp values into the system, compute the fuzzy inference, and obtain a crisp output (defuzzification).

### 1. Restaurant Tipping System (`restaurant_tipping()` function)

This system simulates how a person might decide on a tip based on their perception of service and food quality. Let's break it down:
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# Define input and output variables
service = ctrl.Antecedent(np.arange(0, 11, 1), 'service') # Service quality from 0-10
food = ctrl.Antecedent(np.arange(0, 11, 1), 'food')     # Food quality from 0-10
tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')       # Tip percentage from 0-25%

# Define membership functions
# `automf(3)` automatically creates 'poor', 'average', 'good' membership functions
service.automf(3)
food.automf(3)

# For tip, specific triangular membership functions are defined manually
tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])      # Low tip: 0-13%
tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])  # Medium tip: 0-25% (peaking at 13%)
tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])   # High tip: 13-25%

# Define fuzzy rules
# These are IF-THEN statements that capture human-like reasoning
rule1 = ctrl.Rule(service['poor'] | food['poor'], tip['low']) # IF service is poor OR food is poor, THEN tip is low
rule2 = ctrl.Rule(service['average'], tip['medium'])          # IF service is average, THEN tip is medium
rule3 = ctrl.Rule(service['good'] | food['good'], tip['high'])  # IF service is good OR food is good, THEN tip is high

# Create the fuzzy control system
tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

# Create a simulation to compute the output based on inputs
tipping = ctrl.ControlSystemSimulation(tipping_ctrl)

# Input values for service and food quality
tipping.input['service'] = 6.5
tipping.input['food'] = 9.8

# Compute the fuzzy inference
tipping.compute()

# Print the defuzzified output (the crisp tip value)
print(f"Tip: {tipping.output['tip']:.2f}")

# Visualize the membership functions and the computed output
# tip.view(sim=tipping) # This line is commented out in the original, but useful for visualization

"""### 2. ABS Brake System (`abs_brake_system()` function)

This system simulates a simplified Anti-lock Braking System (ABS) that adjusts brake pressure based on vehicle speed and wheel slip. This is a common application for fuzzy logic in control engineering.
"""

# Define input and output variables
speed = ctrl.Antecedent(np.arange(0, 101, 1), 'speed') # Vehicle speed from 0-100 (e.g., km/h or mph)
slip = ctrl.Antecedent(np.arange(0, 11, 1), 'slip')   # Wheel slip from 0-10 (higher means more slip)
brake = ctrl.Consequent(np.arange(0, 101, 1), 'brake') # Brake pressure from 0-100% (e.g., control signal)

# Define membership functions for inputs (automatically generated)
speed.automf(3)
slip.automf(3)

# Define membership functions for output (manually defined triangular functions)
brake['low'] = fuzz.trimf(brake.universe, [0, 0, 50])        # Low brake pressure
brake['medium'] = fuzz.trimf(brake.universe, [0, 50, 100])  # Medium brake pressure
brake['high'] = fuzz.trimf(brake.universe, [50, 100, 100]) # High brake pressure

# Define fuzzy rules
# These rules dictate how brake pressure changes based on speed and slip
rule1 = ctrl.Rule(speed['poor'] | slip['poor'], brake['high']) # If speed is low OR slip is low (e.g., starting to spin), THEN brake high
rule2 = ctrl.Rule(speed['average'], brake['medium'])           # If speed is average, THEN brake medium
rule3 = ctrl.Rule(speed['good'] | slip['good'], brake['low'])    # If speed is high OR slip is high (e.g., good grip), THEN brake low

# Create the fuzzy control system
braking_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

# Create a simulation to compute the output
braking = ctrl.ControlSystemSimulation(braking_ctrl)

# Input values for speed and slip
braking.input['speed'] = 70
braking.input['slip'] = 3

# Compute the fuzzy inference
braking.compute()

# Print the defuzzified output (the crisp brake pressure value)
print(f"Brake: {braking.output['brake']:.2f}")

# Visualize the membership functions and the computed output
# brake.view(sim=braking) # This line is commented out in the original, but useful for visualization

"""### Visualization (`plt.show()`)

The `plt.show()` command at the end of the script is crucial. If the `.view(sim=...)` lines were uncommented within the functions, `plt.show()` would display the generated plots of the membership functions and the defuzzified output, providing a visual understanding of how the fuzzy system processed the inputs to arrive at the outputs.

In summary, the code sets up two fuzzy logic systems by defining input/output variables, their linguistic terms (e.g., 'poor', 'medium', 'high') with corresponding membership functions, and a set of IF-THEN rules. It then simulates these systems with specific inputs to produce crisp outputs, demonstrating the power of fuzzy logic for decision-making in complex or imprecise scenarios.
"""

pip install scikit-fuzzy