# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rafneta/CienciaDatosPythonCIDE/blob/master/Laboratorios/Lab2/lab2.ipynb

# Laboratorio 2



<div class = "slide-w">
<div class = "video-container">
<iframe src="https://slides.com/ra_fa/labcdpcide/fullscreen#/2" width="100%" height="650px" scrolling="no" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
</div>
"""

#LIST
#Create a list of 10 integers

Number = [1,2,3,4,5,6,7,8,9,10]
print('Original list :', Number)

#sum, max and min
print('Sum:', sum(Number))
print('Maximum:', max(Number))
print('Minimum:', min(Number))

#add and remove elements from list
Number.append(11)
Number.remove(6)
print('Updated list:', Number)

#sorting in ascending and descending order
print('Ascending:', sorted(Number))
print('Descending:',sorted(Number, reverse=True))

#TUPLE
#tuple with 5 strings

food = ('biryani', 'pulao', 'korma', 'pasta','pizza')
print('Food I like is:', food)

#access and print
print('second element is:', food[1])
print('last element is:', food[-1])


#converting tuple into list
food_list = list(food)
print('Tuple converted to a list:', food_list)

#modifying list
food_list[3] = 'cheese cake'
print('modified list is', food_list)

#SETs

set1 = {1,2,3}
set2 = {7,8,9}

#union, intersection, difference
print('Union:', set1.union(set2))
print('Intersection:', set1.intersection(set2))
print('Difference:', set1.difference(set2))

#DICTIONARY

Stars = {'kim taehyung':100, 'Jeon jungkook':99.999, 'Cha eunwoo': 99.99,'Rowoon':99.9 }

#print keys and values
print('Keys:',Stars.keys())
print('Values:',Stars.values())

#update value
Stars['Jeon jungkook']= 100
print('updated dictionary:', Stars)