# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_87OvAF4b7LmNlh7YbO8Rxepxr36VUF
"""



#if we use queue instead of heap it will result in ATTR



import queue

#  Weighted graph: each node maps to a dict of neighbors and edge costs (distances)
graph = {
    "Lahore": {"Islamabad": 270, "Faisalabad": 180},
    "Islamabad": {"Lahore": 270, "Peshawar": 190},
    "Faisalabad": {"Lahore": 180, "Multan": 220},
    "Multan": {"Faisalabad": 220, "Karachi": 880},
    "Peshawar": {"Islamabad": 190},
    "Karachi": {"Multan": 880}
}
# Heuristic must be admissible (never overestimate) to guarantee optimality.
heuristic = {
    "Lahore": 1210,
    "Islamabad": 1100,
    "Faisalabad": 1050,
    "Multan": 880,
    "Peshawar": 1250,
    "Karachi": 0
}
def a_star(graph, start, goal, heuristic):
    """
    A* search returns (path, total_cost) or (None, inf) if no path found.
    We store paths in the priority queue together with their f-cost = g + h.
    """
    open_list = []  # priority queue (min-heap) storing tuples (f_cost, path_list)
    #  push the start node. g(start)=0 so f = 0 + h(start) = h(start)
    queue.queuepush(open_list, (heuristic[start], [start]))
    g_costs = {start: 0}  #  dictionary to store best-known g(n) costs
    closed_set = set()    #  nodes whose best cost is finalized

    #  loop until there are no nodes left to expand
    while open_list:
        f, path = queue.queuepop(open_list)  # pop node with smallest f(n)
        node = path[-1]                     # current node is the last in the path

        #  goal test
        if node == goal:
            return path, g_costs[node]

        # skip if we already finalized this node
        if node in closed_set:
            continue

        closed_set.add(node)  #  mark node as finalized

        # iterate through neighbors and edge costs
        for neighbor, cost in graph[node].items():
            tentative_g = g_costs[node] + cost  # g through current node to neighbor

            # if neighbor unseen or we found a cheaper g, update
            if neighbor not in g_costs or tentative_g < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g
                f_cost = tentative_g + heuristic.get(neighbor, float('inf'))
                new_path = path + [neighbor]
                queue.queuepush(open_list, (f_cost, new_path))

    # if open_list empties without reaching goal => no path
    return None, float('inf')

# Example run
if __name__ == "__main__":
    start_city = "Lahore"
    goal_city = "Karachi"
    path, cost = a_star(graph, start_city, goal_city, heuristic)
    print("A* path:", path)
    print("Total cost:", cost)

import heapq                    # Import heapq to use a priority queue (min-heap)

#  Weighted graph: each node maps to a dict of neighbors and edge costs (distances)
graph = {
    "Lahore": {"Islamabad": 270, "Faisalabad": 180},
    "Islamabad": {"Lahore": 270, "Peshawar": 190},
    "Faisalabad": {"Lahore": 180, "Multan": 220},
    "Multan": {"Faisalabad": 220, "Karachi": 880},
    "Peshawar": {"Islamabad": 190},
    "Karachi": {"Multan": 880}
}
# Heuristic must be admissible (never overestimate) to guarantee optimality.
heuristic = {
    "Lahore": 1210,
    "Islamabad": 1100,
    "Faisalabad": 1050,
    "Multan": 880,
    "Peshawar": 1250,
    "Karachi": 0
}

def a_star(graph, start, goal, heuristic):
    """
    A* search returns (path, total_cost) or (None, float('inf')) if no path found.
    We store paths in the priority queue together with their f-cost = g + h.
    """
    # The open list is a priority queue storing tuples of (f_cost, path_list).
    # The f_cost is the estimated total cost from start to goal through the current node.
    open_list = []

    # Initialize the open list with the start node.
    # The f-cost for the start node is 0 (g-cost) + heuristic[start] (h-cost).
    heapq.heappush(open_list, (heuristic[start], [start]))

    # g_costs stores the best-known cost from the start node to each visited node.
    g_costs = {start: 0} #if we set initial value 0 it will change total cost

    # The closed set stores nodes whose best path from the start has been finalized.
    closed_set = set()

    # Continue searching as long as there are nodes to explore in the open list.
    while open_list:
        # Pop the node with the smallest f-cost from the priority queue.
        f_cost, current_path = heapq.heappop(open_list)
        current_node = current_path[-1]  # The current node is the last in the path

        # If the current node is the goal, we have found the optimal path.
        if current_node == goal:
            return current_path, g_costs[current_node]

        # If the current node has already been finalized, skip it.
        if current_node in closed_set:
            continue

        # Mark the current node as finalized.
        closed_set.add(current_node)

        # Explore the neighbors of the current node.
        for neighbor, edge_cost in graph[current_node].items():
            # Calculate the tentative g-cost for the neighbor.
            tentative_g_cost = g_costs[current_node] + edge_cost

            # If the neighbor has not been visited or we found a cheaper path to it, update its cost.
            if neighbor not in g_costs or tentative_g_cost < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g_cost
                # Calculate the f-cost for the neighbor.
                # Use float('inf') as a default heuristic if the neighbor is not in the heuristic dictionary.
                f_cost = tentative_g_cost + heuristic.get(neighbor, float('inf'))
                # Create a new path including the neighbor.
                new_path = current_path + [neighbor]
                # Add the neighbor to the open list with its f-cost and path.
                heapq.heappush(open_list, (f_cost, new_path))

    # If the open list is empty and the goal has not been reached, no path exists.
    return None, float('inf')

# Example run
if __name__ == "__main__":
    start_city = "Lahore"
    goal_city = "Karachi"
    path, cost = a_star(graph, start_city, goal_city, heuristic)
    print("A* path:", path)
    print("Total cost:", cost)